# Generated by Django 5.0.13 on 2025-12-07 21:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='The title of the blog post.', max_length=200, unique=True)),
                ('slug', models.SlugField(blank=True, help_text='A user-friendly URL for the post.', max_length=200, unique=True)),
                ('content', models.TextField(help_text='The main content of the post.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date and time the post was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The date and time the post was last updated.')),
                ('published', models.BooleanField(default=False, help_text='Whether or not the post is visible to the public.')),
                ('author', models.ForeignKey(help_text='The author of the post.', on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
                'ordering': ['-created_at'],
            },
        ),
    ]
